services:
  postgres:
    container_name: debezium-postgres-db
    image: postgres
    networks:
      - debezium-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: debezium-user
      POSTGRES_DB: debezium-db
      POSTGRES_PASSWORD: debezium-password
    command: [ "postgres", "-c", "wal_level=logical" ]

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: debezium-zookeeper
    networks:
      - debezium-net
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:6.2.0
    hostname: kafka
    container_name: debezium-kafka
    networks:
      - debezium-net
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10

  schema-registry:
    container_name: debezium-schema-registry
    image:  confluentinc/cp-schema-registry
    hostname: schema-registry
    networks:
      - debezium-net
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      PORT: 8081
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
 
  schema-registry-ui:
    image: landoop/schema-registry-ui
    container_name: debezium-schema-registry-ui
    hostname: schema-registry-ui
    networks:
      - debezium-net
    ports:
      - "8000:8000"
    environment:
      SCHEMAREGISTRY_URL: http://schema-registry:8081
      PROXY: "true"
      ALLOW_GLOBAL: "true"
      ALLOW_TRANSITIVE: "true"
      ALLOW_DELETION: "true"
    depends_on:
      - schema-registry
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10

  kafka-ui:
    container_name: debezium-kafka-ui
    image: provectuslabs/kafka-ui:latest
    networks:
      - debezium-net
    ports:
      - "9001:8080"
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10

  debezium:
    image: debezium/connect:1.4
    container_name: debezium-connect
    networks:
      - debezium-net
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
networks:
  debezium-net: